build:
  image: docker:20.10.8
  stage: build
  services:
    - docker:20.10.8-dind
  script:
    - echo $HUB_PUSH_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin registry-1.docker.io
    - make
