FROM python:3.11-slim-bullseye
RUN pip3 install pygments
FROM spacedot/build-base AS cppcheck-build-env

ARG CPPCHECK_VERSION_TAG
# Build cppcheck (rundeps: pcre for rules, python for misra)
# PCRE is recommended for rules, python3 is for misra checker and build optimizations

RUN apt-get install --yes --no-install-recommends libpcre3-dev tidy libxml2-utils

RUN git clone --depth 1 --branch ${CPPCHECK_VERSION_TAG} https://github.com/danmar/cppcheck
WORKDIR /root/cppcheck/build
RUN cmake .. -DHAVE_RULES=ON -DUSE_MATCHCOMPILER=ON -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -GNinja
RUN ninja -j$(nproc)

# Test cppcheck itself, the MISRA plugin and cppcheck-htmlreport
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10
RUN ninja test # run test suite
WORKDIR /root/cppcheck
RUN PYTHONPATH=addons python3 -m pytest addons/test/test-misra.py # run misra tests
RUN ln -s ./build/bin/cppcheck ./cppcheck # prepare for cppcheck-htmlreport test
WORKDIR /root/cppcheck/htmlreport/
RUN bash check.sh

# Pack everything up if all tests went ok (fstrans=no: reason is https://superuser.com/a/1386314)
WORKDIR /root/cppcheck/htmlreport
RUN checkinstall --type=debian --pkgname=cppcheck-htmlreport --pkgversion=${CPPCHECK_VERSION_TAG} \
	--pkgrelease="CUSTOM" --provides=cppcheck-htmlreport --fstrans=no --pakdir=/root/cppcheck/build/ python3 setup.py install

WORKDIR /root/cppcheck/build
RUN checkinstall --type=debian --pkgname=cppcheck --pkgversion=${CPPCHECK_VERSION_TAG} --pkgrelease="CUSTOM" \
	--provides=cppcheck --requires="libpcre3 \(\>= 8.39\)" ninja

# FINAL IMAGE
FROM spacedot/deploy-base AS final

# BeautifulSoup to parse the cppcheck XML
RUN apt install --yes --no-install-recommends
FROM python:3.11-slim-bullseye
RUN pip3 install bs4 lxml pygments

COPY --from=cppcheck-build-env /root/cppcheck/build/*.deb ./

# Install everything
RUN apt install --yes --no-install-recommends ./*.deb 
RUN git clone  https://gitlab.com/acubesat/obc/obc-software.git
RUN cppcheck --enable=all --addon=misra --suppress=misra-c2012-3.1 --suppress=misra-c2012-5.1 --suppress=misra-c2012-5.2 \
      --suppress=misra-c2012-5.3 --suppress=misra-c2012-12.3 --suppress=misra-c2012-13.4 --suppress=misra-c2012-14.4 \
      --suppress=misra-c2012-15.5 --suppress=misra-c2012-16.3 --suppress=misra-c2012-18.4 --suppress=misra-c2012-18.8 \
      --suppress=unusedFunction --suppress=noExplicitConstructor --force --inline-suppr --error-exitcode=1 \
      --xml --xml-version=2 2>report.xml -I ./inc ./src

